version: "3.9"
services:
  db:
    image: postgres:13
    container_name: taskforce-db
    environment:
      POSTGRES_DB: taskforcedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./taskforce-backend
      dockerfile: Dockerfile
    container_name: taskforce-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskforcedb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./taskforce-frontend
      dockerfile: Dockerfile
    container_name: taskforce-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
