services:
  db:
    image: postgres:13
    container_name: taskforce-db
    environment:
      POSTGRES_DB: taskforcedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
